Cargo.lock, Cargo.toml, src/browser.rs, src/cli.rs, src/command.rs, src/command/auth.rs, src/constants.rs, src/main.rs, src/server.rs
Starts local server (localhost:0.0.0.0:0) and open browser with auth redirect url.
Then shut down the server once redirect url is called with auth code.
=> Subcommand: auth login

Cargo.lock, Cargo.toml, schema.json, src/command/deployments/create.rs, src/command/deployments/services/katana.rs
depends on https://github.com/dojoengine/dojo/pull/1518
=> Add `katana` genesis config

Cargo.lock, Cargo.toml, README.md, schema.json, src/command/deployments/accounts.graphql, src/command/deployments/accounts.rs, src/command/deployments/describe.rs, src/command/deployments/logs.rs, src/command/deployments/mod.rs, src/command/deployments/services/katana.rs, src/command/deployments/services/mod.rs
Predeploy PR was accidentally reverted, this just reverts that revert and updates readme
=> Introduce back predeploy

schema.json, src/command/deployments/create.rs, src/command/deployments/describe.rs, src/command/deployments/services/torii.rs, src/command/deployments/update.rs
Pulls new schema from api and makes the following torii params optional:
--rpc
--start-block
--index-pending
=> Pull new schema and make some params optional

Cargo.lock, cli/Cargo.toml, cli/src/command/deployments/delete.rs
=> add confirmation for slot d delete

.graphqlrc.yml, scripts/pull_schema.sh, slot/schema.json
=> Add graphql config for syntax highlighting, add binary docs

cli/src/command/auth/login.rs, slot/src/session.rs
Pending https://github.com/cartridge-gg/controller/pull/608
=> Update slot auth urls

slot/src/session.rs
ref: https://github.com/cartridge-gg/controller/pull/720
=> Lower session's default `expires_at` value

Cargo.lock, Cargo.toml, slot/Cargo.toml
ref: https://github.com/dojoengine/dojo/pull/2454, https://github.com/cartridge-gg/controller/pull/749, https://github.com/cartridge-gg/cainome/pull/54
=> Bump `starknet` to `0.12.0`

Cargo.lock, slot/Cargo.toml
ref: https://github.com/cartridge-gg/controller/pull/757
=> Bump `account_sdk` rev

cli/src/command/deployments/describe.rs, slot/schema.json, slot/src/graphql/deployments/accounts.graphql, slot/src/graphql/deployments/create.graphql, slot/src/graphql/deployments/describe.graphql, slot/src/graphql/deployments/update.graphql
Corrected the usage of the `config` field to `configFile` in CLI and GraphQL schema definitions to align with the updated schema structure.
=> fix(deployments): update config field usage

cli/src/command/deployments/describe.rs, slot/schema.json
Prints the deployment version when describing a deployment.
=> feat(deployments): add version display in describe, refresh schema

slot/src/graphql/auth/update-me.graphql
Added username, slotBilling, and email fields to the update-me mutation response. This ensures all necessary user data is returned.
=> fix(auth): include fields in update-me mutation

cli/src/command/deployments/create.rs, cli/src/command/deployments/services/katana.rs, slot/schema.json
Updated field names and related references for clarity in purpose.
=> refactor(katana): rename `persistent` to `provable`

.github/workflows/release.yml
Upgraded upload-artifact and download-artifact actions to v4.
=> ci: update actions to latest upload/download versions

CONTRIBUTING.md
Hello
I fixed some minor spelling issues.
=> doc fix CONTRIBUTING.md

cli/src/command/auth/info.rs, slot/src/account.rs, slot/src/credential.rs, slot/src/graphql/auth/info.graphql, slot/src/graphql/auth/mod.rs
Updated field naming in structs, tests, and queries to improve clarity and ensure consistency across the codebase.
=> fix(auth): replace `name` field to `username`

Cargo.lock, cli/Cargo.toml, cli/src/command/deployments/create.rs, cli/src/command/deployments/update.rs
This reverts commit 39552a021c554a7e58f92a949acba729bf293217.
=> Revert "fix: bump dojo and adjust types (#210)"

.github/workflows/e2e.yml, scripts/e2e.sh
Added `scripts/e2e.sh` to perform end-to-end testing. Updated the CI workflow to include an `e2e` job that executes the new test script.
=> feat(ci): add e2e test script and workflow integration

slot/src/graphql/team/members.graphql
Aligned GraphQL schema with new input types for team and accounts.
=> fix(graphql): update team member queries and mutations

cli/src/command/auth/transfer.rs
Introduced options to transfer funds in USD or credits. Updated the CLI to validate input such that only one of --usd or --credits is specified. Improved user balance and team balance displays to include both credits and USD conversions.
=> feat(auth): add support for USD and credits transfer

cli/src/command/deployments/update.rs
=> Revert "feat: make config file parameter optional for torii deployment updates"

cli/src/command/auth/info.rs, slot/src/graphql/auth/info.graphql
Added `incubatorStage` and `totalDebits` fields to the GraphQL schema and updated the CLI output to display these values. Includes proper formatting for total debits in USD.
=> feat(auth): add incubator stage and total debits fields

cli/src/command/merkle_drops/create.rs, cli/src/command/merkle_drops/snapshot.rs
Fix create merkle drop from json or params.
Updates snapshot json to accept hex string and numbers.
=> fix(merkle-drops): create from snapshot

cli/src/command/merkle_drops/create.rs, slot/schema.json, slot/src/graphql/merkle_drop/create.graphql, test_merkle_drop.json
Network input for create from json/param accepts ETHEREUM, STARKNET, ARBITRUM, OPTIMISM, POLYGON, BASE
Update preset later when needed.
=> fix(merkle-drops): update network
