cartridge-gg/slot

Cargo.lock, Cargo.toml, src/browser.rs, src/command/auth.rs, src/constant.rs, src/main.rs, src/server.rs
1. Run `slot auth login` on terminal
1. Start local server with `0.0.0.0:0/callback` endpoint
1. Open https://x.cartridge.gg/slot/auth with `callback_uri` param
1. User login/signup in the browser or redirect to consent page if controller already exists
1. User either authorise or deny the consent
1. Redirect to `api.cartridge.gg/oauth2/auth?client_id=cartridge&redirect_uri=<success-uri>&state=<callback-uri>`
1. The server redirects to `x.cartridge.gg/slot/auth/success` with code param
1. Send a post request to callback endpoint with code param
1. Shutdown the local server
1. Send post request to `api.cartridge.gg/oauth2/token` endpoint with the code just retrieved
1. Save token locally as `<dirs::config_local_dir()>/slot/credentials.json`
1. Console out success message
1. Redirect to …
=> Handle auth login callback

Cargo.lock, Cargo.toml, schema.json, src/api.rs, src/command/deployments/create.rs, src/command/deployments/fork.graphql, src/command/deployments/fork.rs, src/command/deployments/mod.rs, src/command/deployments/services/katana.rs, src/command/deployments/services/mod.rs, src/command/deployments/update.rs
Support forking command to fork a katana service, copies katana configs in the fork. If the service is owned by user the seed will also be copied. 
If fork_block_number is not provided we query for latest block and use that
`slot deployments fork {project} {service} --fork-name {name} --fork-block-number {number}`
=> Support fork deployment

Cargo.lock, Cargo.toml, schema.json, src/command/deployments/accounts.graphql, src/command/deployments/accounts.rs, src/command/deployments/mod.rs, src/command/deployments/services/katana.rs, src/command/deployments/services/mod.rs
Resolves https://github.com/cartridge-gg/slot/issues/18
`slot deployments accounts project_name katana` dumps either the predeployed from genesis OR the ones generated from seed. Print format is the same as katana startup
=> Implement retrieving predeployed accounts

src/api.rs, src/command/auth/info.graphql, src/command/auth/info.rs, src/command/auth/mod.rs, src/command/deployments/accounts.rs, src/command/deployments/create.rs, src/command/deployments/delete.rs, src/command/deployments/describe.rs, src/command/deployments/fork.rs, src/command/deployments/list.rs, src/command/deployments/logs.rs, src/command/deployments/update.rs, src/command/teams/members.rs, src/credential.rs, src/server.rs
- save account info in `credentials.json`
- refactor the `ApiClient` to expose associated methods for each api path
- request the account info on auth callback
=> refactor: extra account info in credentials

Cargo.lock, Cargo.toml, src/command/auth/info.graphql, src/credential.rs
- **add test for loading credentials file**
- **include webauthn id in graphql query**
=> Include Webauthn ID in graphql query + test loading credentials

Cargo.lock, Cargo.toml, cli/src/command/auth/session.rs, slot/Cargo.toml, slot/src/session.rs
related to https://github.com/dojoengine/dojo/pull/2303
update to new version of account sdk as it introduces breaking changes to the underlying contract, as well as the keychain now returns a different object (ie `SessionMetadata`) replacing the need to define the struct ourselves
=> bump `account_sdk`

cli/src/command/deployments/create.rs, cli/src/command/deployments/fork.rs, cli/src/command/deployments/mod.rs, cli/src/command/deployments/update.rs
Introduced the 'Common' tier option in the deployment commands for create, update, and fork. This change expands the tier selection, aligning it with the new requirements. Updated related enums and match statements accordingly to integrate the new tier.
=> Add support for Common tier in deployment commands

.github/workflows/release-dispatch.yml
Integrated auto-squash merge step into the GitHub Actions workflow for release preparation. This ensures pull requests are automatically squashed and merged after creation, improving repository cleanliness and history readability.
=> Add auto-squash merge to release-dispatch workflow

cli/src/command/deployments/create.rs, cli/src/command/deployments/services/katana.rs, slot/schema.json
Katana now requires to be explicitly started with `--dev` in order to expose some dev endpoints like `dev_predeployedAccounts`.
This PR aims at adding the support for this option on infra side.
=> feat: add dev mode support for Katana

cli/src/command/deployments/create.rs, cli/src/command/deployments/delete.rs, cli/src/command/deployments/describe.rs, cli/src/command/deployments/logs.rs, cli/src/command/deployments/services/mod.rs, cli/src/command/deployments/services/saya.rs, cli/src/command/deployments/update.rs, slot/schema.json, slot/src/graphql/deployments/create.graphql, slot/src/graphql/deployments/describe.graphql, slot/src/graphql/deployments/update.graphql
Integrated Saya deployment commands and configuration across CLI, GraphQL, and schema files. This allows users to create, update, delete, and describe Saya deployments, with detailed configurations and options specific to the Saya service.
=> Add support for Saya deployments

Cargo.lock, cli/src/command/auth/session.rs, slot/Cargo.toml, slot/src/error.rs, slot/src/lib.rs, slot/src/session.rs
ref: https://github.com/dojoengine/dojo/pull/2303
- bump `account_sdk` rev
- re-export `account_sdk` so that Dojo don't have to manually sync the `account_sdk` version
- update the session creation logic
=> Update to new `account_sdk` session creation logic

slot/src/credential.rs
Load credentials from SLOT_AUTH env variable if set, else from file. This allows for easier configuration management and flexibility in different deployment environments.
=> Add environment variable support to credential loading

cli/src/command/deployments/logs.rs
Simplify the deployment logs retrieval by removing the error handling for GraphQL responses. Now the code directly assigns the query response to the `logs` variable, streamlining the process.
=> Refactor deployment logs query handling

.github/workflows/release.yml
Updated the GitHub Actions workflow to create regular releases instead of draft releases. This modification ensures that the releases are immediately available upon execution, streamlining the release process.
=> Change draft release to regular release

delete.sh
The delete.sh script was responsible for deleting specific deployments sequentially. Given recent changes in deployment practices, this script is now obsolete and no longer necessary in the repository.
=> Remove delete.sh script

slot/Cargo.toml
Specify exact rev to avoid downstream crates from resolving to the latest rev in the main branch.
=> Pin `account_sdk` to rev `61d2fd0`

Cargo.lock, cli/src/command/auth/login.rs, slot/Cargo.toml, slot/src/account.rs, slot/src/credential.rs, slot/src/error.rs, slot/src/graphql/auth/mod.rs, slot/src/session.rs
ref #104.
adding this back as Sozo, Katana expects the contract address field to exist in order to perform certain operations - [generating policies](https://github.com/dojoengine/dojo/blob/77042b16c2002cf22a1529204ae7102420dcc634/bin/sozo/src/commands/options/account/controller.rs#L80), [injecting controller account](https://github.com/dojoengine/dojo/blob/77042b16c2002cf22a1529204ae7102420dcc634/crates/katana/controller/src/lib.rs#L30-L53).
i've also changed the error handling to just return a generic `MalformedCredentials` error when the deserialization fails.
=> fix: add back the account address field in credentials

slot/src/account.rs
we're using the types in the `account.rs` for some tests in the Dojo repo
https://github.com/dojoengine/dojo/blob/77042b16c2002cf22a1529204ae7102420dcc634/crates/katana/controller/src/lib.rs#L219-L234
=> Ensure all types in a public api, are public

slot/schema.json, slot/src/graphql/auth/info.graphql, slot/src/graphql/auth/mod.rs
Introduced ControllerEdge struct and modified Account to utilize it. Updated schema to include new pagination and filtering options for controllers. Added support for CreditsHistory and its related fields, sorting, and filtering options.
=> feat(account): add edge and pagination support for controllers

cli/src/command/deployments/services/torii.rs, cli/src/command/deployments/update.rs, slot/schema.json, slot/src/graphql/deployments/update.graphql
Added the ability to specify a config file for the Torii service on update. The file is read and encoded in base64 for the update process.
=> feat(cli): add config file support for update torii cmd

Cargo.lock, cli/Cargo.toml, cli/src/command/deployments/create.rs, cli/src/command/deployments/services/katana.rs, cli/src/command/deployments/update.rs, slot/schema.json, slot/src/graphql/deployments/update.graphql, slot/src/lib.rs, slot/src/read.rs
Introduced a config file option in deployment commands to allow users to specify and encode configuration files in base64.
=> feat(katana): add config file support for katana

.gitignore, cli/src/command/deployments/create.rs
Updated the RPC field in CreateToriiConfigInput to use the cloned config directly, resolving the issue of incorrect duplication.
=> fix(deployments): correct RPC field duplication error

Cargo.lock, cli/Cargo.toml, cli/src/main.rs
Implement version check and notification using update-informer crate. This informs users of new versions with formatted messages to encourage updates. Updated Cargo.toml and Cargo.lock files to include new dependencies.
=> feat(cli): add version update notification

cli/Cargo.toml
Include 'ureq' feature in update-informer to ensure proper functionality within the CLI.
=> fix(cli): add missing feature in update-informer config

cli/src/command/deployments/update.rs
@steebchen in this PR we enforce a configuration file for Torii. This is what it looks like.
Please let me know your thoughts about it and let's iterate. 👍
=> fix: ensure the config is provided before updating torii

cli/src/main.rs
Set update_informer to check for updates every hour by configuring the interval duration, enhancing update management.
=> feat(cli): add update check interval configuration

slot/schema.json
Added new fields related to achievements and paymasters to the schema, including predicates for filtering and searching these entities. This extends the schema's capability to handle achievement metadata and paymaster-related data more comprehensively.
=> feat(schema): sync schema with api

Cargo.lock, Cargo.toml, cli/Cargo.toml
This update ensures the new torii and katana `Args` are available in slot.
Had to change serde to match dependencies.
=> chore: update dojo cli

CONTRIBUTING.md
Added steps for running cartridge API locally and environment variable configuration to CONTRIBUTING.md for easier local development setup.
=> docs(contributing): add instructions for local API setup

cli/src/command/auth/fund.rs, cli/src/command/auth/mod.rs
Introduced a new "Fund" command for authenticated users. This command opens the browser to direct users to the funding page.
=> feat(auth): add fund command to support user account funding

scripts/pull_schema.sh
Allow specifying "local" or "prod" to pull schema from the desired environment. Display usage instructions for invalid inputs.
=> chore(scripts): add param for local/prod schema pull

cli/src/command/deployments/create.rs, cli/src/command/deployments/services/katana.rs, slot/schema.json
Introduce `persistent` and `network` options to Katana service. The `network` option is validated to require `--persistent` mode.
=> feat(katana): add persistent mode and network options

cli/src/command/deployments/create.rs, cli/src/command/deployments/services/katana.rs, slot/schema.json
Added a new `saya` option to Katana services, usable only in
provable mode. Updated validation logic and schema for compatibility.
=> feat(katana): add saya option for provable mode

.github/workflows/release.yml
Update artifact naming to include job target and enable pattern-based artifact download with merged artifacts handling.
=> ci: adjust release artifact naming and downloading

cli/src/command/deployments/create.rs, cli/src/command/deployments/mod.rs, cli/src/command/deployments/update.rs, slot/schema.json
Updated CLI commands and schema to replace "Rare" tier with the new "Insane" tier for deployments. Removed deprecated "uncommon" tier from schema.
=> feat(deployments): add "Insane" tier and remove "Rare" tier

cli/src/command/deployments/mod.rs, cli/src/command/deployments/transfer.rs, cli/src/command/mod.rs, cli/src/command/teams/create.rs, cli/src/command/teams/mod.rs, slot/schema.json, slot/src/graphql/deployments/mod.rs, slot/src/graphql/deployments/transfer.graphql, slot/src/graphql/deployments/transfer.rs, slot/src/graphql/team/create.graphql, slot/src/graphql/team/mod.rs, slot/src/graphql/team/teams.graphql
Introduces commands to create teams and transfer deployments between teams in the CLI. Adds respective GraphQL queries and updates schema to support new operations.
=> feat(cli): add support for team creation and transfer

cli/src/command/auth/info.rs, slot/src/graphql/auth/info.graphql
Updated GraphQL schema and CLI output to use `username` instead of `name` for account info to ensure consistency across displays.
=> fix(auth): update field name to username in account info

cli/src/command/deployments/create.rs
This makes the URL clickable without breaking.
=> fix(deployments): correct spacing in deployment output text

cli/src/command/deployments/describe.rs, slot/schema.json, slot/src/account.rs, slot/src/credential.rs, slot/src/graphql/auth/mod.rs, slot/src/graphql/deployments/describe.graphql
Added a `deprecated` field to the GraphQL query and CLI output to inform users when a deployment is deprecated.
=> chore: refresh gql schema

cli/src/command/deployments/describe.rs
Added additional spacing and a "NOTE:" label to improve the clarity of the deprecation message in deployment descriptions.
=> fix(deployments): improve deprecated warning formatting

.github/workflows/release.yml
Add CMAKE_POLICY_VERSION_MINIMUM to ensure compatibility with CMake.
=> ci: update release workflow with CMake policy variable

.github/workflows/ci.yml
Added CMAKE_POLICY_VERSION_MINIMUM to ensure-windows job in CI.
=> ci: add env variable to Windows workflow configuration

cli/src/command/deployments/create.rs, slot/src/graphql/deployments/create.graphql
Added optional team parameter to deployment creation command and GraphQL schema, allowing users to specify a team for deployments. Defaults to the username-based team if not provided.
=> feat(deployments): add team support for deployments

scripts/test-capacity.sh
Introduce `test-capacity.sh` to handle batch creation and deletion of deployments with retry logic for robustness. This script improves efficiency in managing large-scale deployment tasks.
=> feat(scripts): add test-capacity script for batch ops

slot/schema.json, slot/src/graphql/team/teams.graphql
Updated fields in schema and GraphQL queries to use 'name' instead
of 'teamID', ensuring consistency and aligning with the expected
data structure.
=> fix(slot): use name in team related queries

Cargo.lock, cli/Cargo.toml, cli/src/main.rs, slot/Cargo.toml, slot/src/api.rs, slot/src/lib.rs, slot/src/version.rs
Refactored version update logic into a dedicated module `slot::version`. Integrated update checks into CLI and API error handling for consistency. Updated dependencies for `colored` and `update-informer`.
=> feat(version): centralize checks & notify on API error

cli/src/command/auth/transfer.rs, cli/src/command/teams/mod.rs, cli/src/command/teams/update.rs, slot/schema.json, slot/src/graphql/team/create.graphql, slot/src/graphql/team/mod.rs, slot/src/graphql/team/update.graphql
Introduced `updateTeam` mutation and CLI command to update team details such as email. Updated schema and GraphQL queries to support new fields.
=> feat(teams): add update functionality for teams

cli/src/command/auth/transfer.rs
Corrected the displayed USD conversion values in transfer output to use updated balances instead of previous balances.
=> fix(auth): correct balance calculations in transfer output

cli/src/command/auth/info.rs, slot/schema.json, slot/src/graphql/auth/info.graphql, slot/src/graphql/auth/mod.rs
Added creditsPlain field to GraphQL schema and updated CLI to display user credits in both integer and dollar formats. Improved output for empty teams and deployments.
=> feat(auth): add creditsPlain field to user info

slot/Cargo.toml
Added the "serde" feature to the num-bigint crate to ensure proper serialization and deserialization support.
=> fix(slot): enable serde support for num-bigint dependency

slotup/slotup
Added a mechanism to verify if the installed version of `slot` matches the latest version, skipping reinstallation when current and latest versions align.
=> feat(slotup): add version check to skip reinstall

Cargo.lock, README.md, cli/src/command/mod.rs, cli/src/main.rs, slot/Cargo.toml, slot/src/api.rs, slot/src/version.rs, slotup/slotup
Introduced auto-update support for the CLI using `slotup`. Checks for a new version and triggers an update if applicable. Added environment variable control and binary checks for flexibility.
=> feat(cli): add auto-update functionality

cli/src/command/paymaster/info.rs, cli/src/command/paymaster/stats.rs
```🔍 Paymaster Info for 'test'
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🏢 Details:
• Team: test-team
• Active: ✅ Yes
💰 Budget:
• Total: 9000 CREDIT ($90.00 USD)
• Spent: 141.78 CREDIT ($1.42 USD)
• Usage: [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 1.3%
📋 Policies:
• Count: 12
```
```
📊 Paymaster Stats for 'test' (Last 1hr)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📈 Transactions:
• Total: 2824
• Successful: 2710
• Reverted: 114
• Success Rate: 96.0%
• TPS: 0.7844
```
=> feat(paymaster): add percentage bar to budget and tps

CLAUDE.md
Added a new documentation file, CLAUDE.md, outlining the project's overview, tech stack, commands, architecture, environment variables, and development notes. Contains detailed guidance for contributors working with the CLI tool and execution layer.
=> docs(slot): add CLAUDE.md with project guidance

cli/src/command/deployments/mod.rs
Added a warning message for 'db_dir' found in the config file, notifying users that it is ignored and managed by the system.
=> feat(deployments): warn about ignored db_dir in config

cli/src/command/auth/mod.rs, cli/src/command/auth/token.rs
Introduced a new `token` command to display the current authentication token. Includes usage instructions for programmatic authentication, useful in CI/CD pipelines or scripts where interactive authentication is not feasible.
=> feat(auth): add token command for auth token display

cli/src/command/teams/invoices.rs, cli/src/command/teams/mod.rs, slot/src/graphql/team/invoices.graphql, slot/src/graphql/team/mod.rs
Introduced a new `Invoices` subcommand under teams to fetch and display team invoices. Supports listing up to 100 invoices, ordering by creation date in descending order, and formatting monetary values. Added new GraphQL query `TeamInvoices` for fetching invoices data.
=> feat(teams): add invoices subcommand to list team invoices

.github/workflows/schema-sync.yml, slot/schema.json
Added a GitHub Actions workflow to automate daily syncing of the GraphQL schema from the production API. The workflow runs daily at 2 AM UTC and creates pull requests with schema updates for streamlined review and integration. Includes manual triggering support for on-demand updates.
=> ci(workflows): add daily GraphQL schema sync workflow
